name: Python test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
      
jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python_version: ["3.8", "3.9", "3.10"]
        exclude:
          - os: macos
            python_version: "3.8"
          - os: macos
            python_version: "3.9"
          - os: windows
            python_version: "3.8"
          - os: windows
            python_version: "3.9"
            
    steps:          
      - uses: actions/checkout@v3
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          channels: conda-forge
          extra-specs: |
            python=${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox          
      - name: Run `nox -s tests`     
        run: python -m nox -s tests-${{ matrix.python_version }}