name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: nox -s lint mypy
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v3
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          environment-name: ci
          channels: conda-forge
          extra-specs: |
            python=3.9
            mamba
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox         
      - name: Run `nox -s lint`
        shell: bash -l {0}      
        run: python -m nox -s lint
      - name: Run `nox -s mypy`
        shell: bash -l {0}
        run: python -m nox -s mypy